src/frontend/csrs-portal/.devcontainer/post-create.sh
src/frontend/csrs-portal/.gitignore
src/frontend/csrs-portal/package-lock.json
src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.scss
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/shared/components/header/header.component.html
src/frontend/csrs-portal/src/app/shared/components/header/header.component.scss
src/frontend/csrs-portal/src/assets/Info_rollover_icon.svg
src/frontend/csrs-portal/src/assets/Support_icon.svg

- CSRS-81: updated Landing page by new requirements

updated landing

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/assets/Down-chevron-icon.svg

- CSRS-227 refactoring questionnaire

feat: [CSRS-227] refactoring questionnaire

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.scss

- fixed icon's issue on the landing page
- [x ] Bug fix (non-breaking change which fixes an issue)

fixed icon issue on Landing page

---

docker-compose.yml
src/backend/Csrs.Api/Configuration/CsrsConfiguration.cs
src/backend/Csrs.Api/Configuration/CsrsEnvironmentVariablesConfigurationProvider.cs
src/backend/Csrs.Api/Configuration/JaegerConfiguration.cs
src/backend/Csrs.Api/Configuration/SerilogExtensions.cs
src/backend/Csrs.Api/Configuration/SplunkConfiguration.cs
src/backend/Csrs.Api/Csrs.Api.csproj
src/backend/Csrs.Api/Instrumentation/InstrumentationExtensions.cs
src/backend/Csrs.Api/Program.cs
src/backend/Csrs.Api/Properties/launchSettings.json
src/backend/Csrs.Api/appsettings.json

- fixes issue with docker compose where I previously changed the config to use container name instead of service
- adds additional logging attributes, machine name, process id, thread id, context info, git sha and branch name
- remove https redirection as on openshift, api is not exposed externally

Logging changes

---

src/backend/Csrs.Api/Configuration/SerilogExtensions.cs
src/backend/Csrs.Api/Csrs.Api.csproj

- comments out the use of the GitVersion tool due to current problem during docker build of backend

remove git version due to docker build problem

---

src/backend/Csrs.Api/Authentication/IOAuthApiClient.cs
src/backend/Csrs.Api/Authentication/ITokenService.cs
src/backend/Csrs.Api/Authentication/OAuthApiClient.cs
src/backend/Csrs.Api/Authentication/OAuthAuthorizationException.cs
src/backend/Csrs.Api/Authentication/OAuthError.cs
src/backend/Csrs.Api/Authentication/TokenService.cs

- enhancements to the oauth login to provide better logging when authentication fails.
- move classes to their own file

Add better error logging when OAuth failures

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.ts

Commented Keycloak options
- [x ] New feature (non-breaking change which adds functionality)
- [ x] No
- [ x] No
- [ x] I have performed a self-review of my own code

Commented Keycloak options

---

src/frontend/csrs-portal/nginx.conf
src/frontend/csrs-portal/src/app/core/services/auth.service.ts

- add add_header Access-Control-Allow-Origin '*'
- [x ] New feature (non-breaking change which adds functionality)
- [x ] No
- [ x] No
- [ x] I have performed a self-review of my own code

add add_header Access-Control-Allow-Origin '*'

---

src/frontend/csrs-portal/nginx.conf
src/frontend/csrs-portal/package.json
src/frontend/csrs-portal/yarn.lock

removed CORS header and added CORS lib
- [ x] New feature (non-breaking change which adds functionality)
- [x ] No

removed CORS header and added CORS lib

---

src/frontend/csrs-portal/nginx.conf
src/frontend/csrs-portal/src/keycloak.spec.ts
src/frontend/csrs-portal/src/keycloak.ts

added header Access-Control-Allow-Credentials  with value true

added header Access-Control-Allow-Credentials  with value true

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.html
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.scss
src/frontend/csrs-portal/src/assets/Application_icon.svg

Validate application

---

src/frontend/csrs-portal/package-lock.json
src/frontend/csrs-portal/package.json
src/frontend/csrs-portal/src/app/app.component.ts
src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/auth/auth-config.module.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/silent-renew.html
src/frontend/csrs-portal/yarn.lock

- added oidc library
- [x ] No
- [x ] I have performed a self-review of my own code

Added oidc library

---

src/backend/Csrs.Api/Controllers/AccountController.cs
src/backend/Csrs.Api/Controllers/CsrsControllerBase.cs
src/backend/Csrs.Api/Controllers/DocumentController.cs
src/backend/Csrs.Api/Controllers/FeedbackController.cs
src/backend/Csrs.Api/Controllers/FileController.cs
src/backend/Csrs.Api/Controllers/LookupController.cs
src/backend/Csrs.Api/Controllers/MessageController.cs
src/backend/Csrs.Api/Controllers/UserRequestController.cs

- Changes the apis to use /api prefix

Change apis to start with /api

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- fixed issue with http response

fixed issue with http response

---

src/frontend/csrs-portal/nginx.conf

- updated nginx.conf by proxy_pass http://jag-csrs-api/api/

updated nginx.conf by proxy_pass http://jag-csrs-api/api/

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- added token in account and lookup services' calls in application component

added token in account and lookup services' calls

---

src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

- [CSRS-32] Initial login to portal

[CSRS-32] Initial login to portal

---

docker-compose.yml
src/backend/Csrs.Api/Configuration/CsrsConfiguration.cs
src/backend/Csrs.Api/Configuration/FileManagerConfiguration.cs
src/backend/Csrs.Api/Csrs.Api.csproj
src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs
src/backend/Csrs.Services.FileManager/Csrs.Services.FileManager.csproj
src/backend/Csrs.Services.FileManager/Dockerfile
src/backend/Csrs.Services.FileManager/Dockerfile.rhel8
src/backend/Csrs.sln
src/backend/README.md

- Add client library for calling file manager

Integrate file manager service

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- fixed issue with apiLookupCourtlocationsGet call in previous PR

fixed issue with apiLookupCourtlocationsGet call

---

src/backend/Csrs.Api/Repositories/CsrsFileRepository.cs

- removed fetching file status of Draft

remove fetching draft files

---

src/backend/Csrs.Api/Features/Accounts/NewAccountAndFile.cs
src/backend/Csrs.Api/Models/Dynamics/Models.generated.cs
src/backend/Csrs.Api/Models/Dynamics/SSG_CsrsFile.cs
src/backend/Csrs.Api/Repositories/CsrsFileRepository.cs
src/backend/Csrs.Api/Repositories/RepositoryExtensions.cs
src/backend/Csrs.Api/Services/FileService.cs
src/backend/Csrs.Test/Repositories/ChildInsertOrUpdateFieldMapperTest.cs
src/utility/CrmSvcUtilExtensions/MappingDefinition.cs

- set the the party enrolled field on create file, remove more draft file status

Add more fields to files

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.scss
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts

- CSRS-270
- CSRS-317
- CSRS-293

added hard coded details to the inbox

---

openshift/jag-csrs-file-manager.yml

- Correct location for Secure Token Service End Point for SharePoint  (CSRS-334)

[CSRS-334] Fix STS endpoint for SharePoint

---

src/frontend/csrs-portal/src/assets/oidc.json

- Updated BCeId redirect URL by new URL dev.childsupportrecalc.gov.bc.ca

Updated BCeId redirect URL by new URL dev.childsupportrecalc.gov.bc.ca

---

src/backend/Csrs.Api/Controllers/DocumentController.cs
src/backend/Csrs.Api/Controllers/FileController.cs
src/backend/Csrs.Api/Dynamics/DynamicsClientExtensions.cs
src/backend/Csrs.Api/Extensions/SharePointDocumentLocation.cs
src/backend/Csrs.Interfaces.Dynamics/Extensions/EntityDocumentExtensions.cs

Move attachment upload to document controller
Remove existing endpoints
Add entity name to upload attachments

Moving Attachment Upload

---

src/backend/Csrs.Api/Features/Accounts/NewAccountAndFile.cs
src/backend/Csrs.Api/Models/File.cs
src/backend/Csrs.Api/Models/LookupValue.cs
src/backend/Csrs.Api/Models/ModelExtensions.cs
src/backend/Csrs.Api/Models/NewFileRequest.cs
src/backend/Csrs.Api/Models/Party.cs
src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/backend/Csrs.Api/Services/FileService.cs
src/backend/Csrs.Api/Services/IFileService.cs
src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs
src/backend/Csrs.Interfaces.Dynamics/ModelExtensions/MicrosoftDynamicsCRMssgCsrsparty.cs
src/backend/Csrs.Interfaces.Dynamics/Ssgcsrsparties.cs
src/backend/Csrs.TntegrationTest/DynamicsClientTestBase.cs
src/backend/Csrs.TntegrationTest/GetPartyTest.cs
src/frontend/csrs-portal/yarn.lock

- updated party/file/child api

updated party/file/child api

---

src/frontend/csrs-portal/angular.json
src/frontend/csrs-portal/nginx.conf
src/frontend/csrs-portal/package.json
src/frontend/csrs-portal/src/app/app.component.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/core/services/snowplow.service.spec.ts
src/frontend/csrs-portal/src/app/core/services/snowplow.service.ts
src/frontend/csrs-portal/src/index.html
src/frontend/csrs-portal/src/snowplow.js
src/frontend/csrs-portal/yarn.lock

-[CSRS -239] Added Snowplow source code

added snowplow

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts

- [CSRS-239] Added snowplow in Questionnaire component

Added snowplow in Questionnaire component

---

src/backend/Csrs.Api/Csrs.Api.csproj
src/backend/Csrs.Interfaces.Dynamics/Csrs.Interfaces.Dynamics.csproj
src/backend/Csrs.Interfaces.SharePoint/SharePoint.csproj
src/backend/Csrs.Services.FileManager/Csrs.Services.FileManager.csproj
src/backend/Csrs.Test/Csrs.Test.csproj
src/backend/Csrs.TntegrationTest/Csrs.TntegrationTest.csproj

- adds a post clean step to remove the bin and obj directories

add post clean to remove bin and obj directories

---

src/backend/Csrs.Api/Controllers/MessageController.cs
src/backend/Csrs.Api/Features/Messages/List.cs
src/backend/Csrs.Api/Features/Messages/Read.cs
src/backend/Csrs.Api/Models/Message.cs
src/backend/Csrs.Api/Models/ModelExtensions.cs
src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/backend/Csrs.Api/Services/IMessageService.cs
src/backend/Csrs.Api/Services/MessageService.cs
src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs
src/backend/Csrs.Test/Controllers/MessageControllerTest.cs
src/backend/Csrs.TntegrationTest/GetCommunicationMessageTest.cs
src/backend/Csrs.TntegrationTest/GetFileTest.cs
src/backend/Csrs.TntegrationTest/GetPartyTest.cs

Update list endpoint to return all messages for logged in user

Get Messages

---

src/backend/Csrs.Api/Features/Messages/List.cs
src/backend/Csrs.Api/Features/Messages/Read.cs
src/backend/Csrs.Api/Models/ModelExtensions.cs
src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/backend/Csrs.Api/Services/IMessageService.cs
src/backend/Csrs.Api/Services/MessageService.cs
src/backend/Csrs.TntegrationTest/GetCommunicationMessageTest.cs

Remove redundant call to to list
Pass cancellation token down 
Update mapper name

Refactoring 

---

src/backend/Csrs.Api/Models/File.cs
src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/backend/Csrs.Api/Repositories/InvalidIdException.cs
src/backend/Csrs.Api/Services/DocumentService.cs

- Adds FileNumber to FileSummary. **Breaking Change**: FileId is the internal `Guid` value that should be used in API calls, the FileNumber is the human readable number that is displayed to the user.
- Adds Escaping of string values used in filter expressions to avoid injection attack
- Adds checking `id` or guid parameters are actually guid before attempting to query.

File summary return file id and file number

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.scss
src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/assets/PDF_icon.svg
src/frontend/csrs-portal/src/assets/Questionnaire-End_icon.svg
src/frontend/csrs-portal/src/scss/material/_material-overrides.scss
src/frontend/csrs-portal/src/scss/material/components/_mat-sidenav.scss

worked on questionnaire styling

---

src/backend/Csrs.Api/Authentication/AuthenticationExtensions.cs

- Add logging to the jwt auth and handler when not authorized 

Add logging to the jwt auth and handler when not authorized

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/shared/components/header/header.component.html
src/frontend/csrs-portal/src/app/shared/components/page-header/page-header.component.scss
src/frontend/csrs-portal/src/scss/material/_material-overrides.scss
src/frontend/csrs-portal/src/scss/vendors/_ng-busy.scss
src/frontend/csrs-portal/src/styles.scss

added styling to questionaire

---

src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

Updated for proper bearer auth call

Updated for proper bearer auth call

---

src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

Fix Auth 2

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

added Bearer token

---

src/frontend/csrs-portal/angular.json
src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/assets/config/oidc.json

Fixing Bearer Token Configuration 

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

Fix bearer set in components second pass

Fix bearer set in components2

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

Fixing bearer set in components

Fixing bearer set in components

---

src/frontend/csrs-portal/src/app/app.module.ts

- removes repeated calls to `authService.getAccessToken()`

avoid repeated calls to getting token

---

src/backend/Csrs.Api/Models/Party.cs
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

removed required attribute for Gender in Party model}

removed required attribute for Gender in Party model

---

src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

replaced apiGateWay by oAuthOptions

replaced apiGateWay by oAuthOptions

---

src/backend/Csrs.Api/ApiGateway/ApiGatewayHandler.cs
src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs

restored previous code

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- fixed party portion (secondFormGroup)

fixed party portion (secondFormGroup)

---

src/backend/Csrs.Api/Features/UserRequests/Create.cs
src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.scss
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts

Tied in contact for to backend
updated backend logging

Added call to API from Contact form.

---

src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs
src/backend/Csrs.Interfaces.Dynamics/Extensions/DynamicsClient.cs
src/backend/Csrs.Interfaces.Dynamics/Extensions/DynamicsClientOptions.cs
src/backend/Csrs.TntegrationTest/DynamicsClientTestBase.cs

Injected Resource URL for Odatabinds

---

src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/styles.scss

- CSRS-264, CSRS-274, CSRS-354

added back button to first question and added styling to the page

---

src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/auth/auth-config.module.ts
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts

updated bearer token and active status

updated bearer token and active status

---

src/backend/Csrs.Api/Services/DocumentService.cs
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts

Updates for Upload Doc Testing in DEV

Updates for Upload Doc Testing in DEV

---

src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs

Re-add ssl check

---

src/backend/Csrs.Api/Features/Accounts/UpdateCSRSAccount.cs

- added bceid and bceidlastupdate fields to update the respondent application in Dynamics

added bceid and bceidlastupdate fields into respondent application

---

src/backend/Csrs.Api/Features/UserRequests/Create.cs

Added creation of task to staff after ContactUs Created

Added creation of task to staff after ContactUs Created

---

src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/auth/auth-config.module.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

updated bceid registration link in the landing component

updated bceid registration link

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts

1) Message Displays
2) Updated DocumentType SelectList
3) Added Validation for Upload tab
4) Update to Alert Banner as per Design Spec (ARIA Labels)

Updates to Communication Page

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.ts

Fix for success popups

---

.gitignore

- re-adds the deleted .gitignore

restore .gitignore that was deleted by accident

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts

fixed misspelling error on error message for respondent application

fixed misspelling error on error message for respondent application

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

[CSRS-361] - fixed birthdate field for child in applicant application

fixed birthdate field for child in applicant application

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

fixed date of court order on step 5 in applicant application

fixed date of court order on step 5 in applicant application

---

src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/auth/auth-config.module.ts

[CSRS-365] - increased time before to check if token was expired

checked token

---

src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs

Fix two for file manager

---

src/frontend/csrs-portal/package.json
src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/auth/auth.guard.ts
src/frontend/csrs-portal/src/app/auth/auth.service.ts
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts
src/frontend/csrs-portal/yarn.lock

fixed issue with token

---

src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/backend/Csrs.Api/WebApplicationBuilderExtensions.cs

Also added filenumber to file fetch for Upload Doc folder name creation

Rollback and fix some changes for grpc service in api

---

src/frontend/csrs-portal/src/app/app-routing.module.ts
src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/auth/auth-config.module.ts
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

- added guard functionality for all components after bceid login

added guard functionality for all components after bceid login

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

disabled / enabled submit application button

disabled / enabled submit application button

---

.github/workflows/build-all-on-tagging.yml
.github/workflows/build-api.yml
docker-compose.yml
openshift/jag-csrs-api.yml
openshift/jag-csrs-deploy-api-from-tagged-candidate.yml
src/backend/CSRS API.postman_collection.json
src/backend/Csrs.Api/Properties/launchSettings.json
src/backend/Dockerfile.rhel8
src/frontend/csrs-portal/nginx.conf
src/frontend/csrs-portal/proxy.conf.json
src/frontend/csrs-portal/src/environments/environment.prod.ts

Refining API Docker Spec

---

src/backend/Csrs.Interfaces.SharePoint/SharePoint.csproj
src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs
src/backend/Csrs.Services.FileManager/Csrs.Services.FileManager.csproj
src/backend/Csrs.Services.FileManager/Services/FileManagerService.cs
src/backend/Csrs.Services.FileManager/Startup.cs

See title. Could do with more cleanup but really wanted to get the changes in to see if we get more info

Remove auth requirement, check some args for null, add logging

---

src/backend/Csrs.Interfaces.SharePoint/Authentication.cs
src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs
src/backend/Csrs.Interfaces.SharePoint/SharepointHealthCheck.cs
src/backend/Csrs.Services.FileManager/Services/FileManagerService.cs

PR to log out issue that may be causing NullReferenceException

Add logging around SharePoint auth to troubleshoot errors

---

src/backend/Csrs.Api/Features/Accounts/UpdateCSRSAccount.cs
src/backend/Csrs.Api/Models/ModelExtensions.cs
src/backend/Csrs.Api/Repositories/DynamicsExtensions.cs
src/backend/Csrs.Api/Services/FileService.cs
src/backend/Csrs.Api/Services/IFileService.cs
src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.scss
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts

CSRS-381, CSRS-371, CSRS-367, CSRS-368}

CSRS-381, CSRS-371, CSRS-367, CSRS-368

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/mailbox/mailbox.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.html
src/frontend/csrs-portal/src/scss/material/_material-overrides.scss

- {CSRS-362, CSRS-363, CSRS-365}

added wording change and tooltip to the questionnaire

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

CSRS369, CSRS368

---

src/backend/Csrs.Api/Features/UserRequests/Create.cs
src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts

Also added New Message Link to TabIndex 2

CSRS-393 Updated OwnerId of ContactUs

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.scss
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts
src/frontend/csrs-portal/src/assets/Download_icon.svg
src/frontend/csrs-portal/src/assets/Message_icon.svg
src/frontend/csrs-portal/src/assets/PDF-black_icon.svg
src/frontend/csrs-portal/src/assets/View_icon.svg

Updated for Inbox

---

src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs

Add parameter null check

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/shared/components/header/header.component.html
src/frontend/csrs-portal/src/app/shared/components/header/header.component.ts

fixed issue with keycloak

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

added cross icon into date of birthday for other party

added cross icon into date of birthday for other party

---

src/backend/Csrs.Api/Features/Accounts/UpdateCSRSAccount.cs

CSRS390: Test Case 007 - Generate a Task for RO in Dynamics when Respondent Files the Respondent Application

developed CSRS390

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

fixed CSRS 380

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html

added csrs392 fix to respondent application

added csrs392 fix to respondent application

---

src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.html

worked on quesetionnaire tooltip

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

developed csrs377

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

developed csrs398

---

src/frontend/csrs-portal/src/app/auth/auth-config.module.ts
src/frontend/csrs-portal/src/assets/config/oidc.json

kc_idp_hint does not work with oidc, removed from configuration and config file

commented kc_idp_hint

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

fixed csrs380

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

developed csrs380

---

src/frontend/csrs-portal/nginx.conf

[CSRS-407] Support for Larger Upload

---

src/frontend/csrs-portal/src/app/app.module.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/services/log-in-out.service.ts
src/frontend/csrs-portal/src/app/shared/components/header/header.component.html
src/frontend/csrs-portal/src/app/shared/components/header/header.component.scss
src/frontend/csrs-portal/src/app/shared/components/header/header.component.ts
src/frontend/csrs-portal/yarn.lock

developed csrs394

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts

- updated csrs394 by call logoffAndRevokeTokens method

updated csrs394 by call logoffAndRevokeTokens method

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts

fixed csrs363

---

.github/workflows/build-all-on-tagging.yml
.github/workflows/build-api.yml
.github/workflows/build-file-manager.yml
.github/workflows/build-frontend.yml
src/frontend/csrs-portal/Dockerfile

- Node docker image version upgrade; that in turn upgraded version of Yarn
- Ubuntu Version Upgrade 

[CSRS-94] Node, Yarn, Ubuntu Versions Upgrade

---

src/frontend/csrs-portal/src/snowplow.js

Changed showplow collector

---

README.md

Update README Fix Badges

---

src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.html
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.scss

responsive design of WelcomeUser component

responsive design of WelcomeUser component

---

src/frontend/csrs-portal/angular.json
src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.ts
src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.html
src/frontend/csrs-portal/src/app/components/welcome-user/welcome-user.component.ts
src/frontend/csrs-portal/src/app/core/services/snowplow.service.ts
src/frontend/csrs-portal/src/app/services/app-config.service.ts
src/frontend/csrs-portal/src/assets/app.config.json
src/frontend/csrs-portal/src/snowplow.js

CSRS375: added all links from CSRS375, snowplow collectro set up to spt

CSRS375: added all links from CSRS375, snowplow collectro set up to spt

---

src/frontend/csrs-portal/src/snowplow.js

-updated snowplow.js by checking the  NODE_ENV setting

updated snowplow.js by checking the  NODE_ENV setting

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/index.html
src/frontend/csrs-portal/src/snowplow.js

- removed snowplow custom code, fixed issue with bceIdRegisterLink

removed snowplow custom code, fixed issue with bceIdRegisterLink

---

.github/workflows/api-only-prod-tagging-deploy.yml
.github/workflows/filemanager-only-prod-tagging-deploy.yml
.github/workflows/frontend-only-prod-tagging-deploy.yml
openshift/jag-csrs-api.yml
openshift/jag-csrs-deploy-api-from-tagged-candidate.yml
openshift/jag-csrs-deploy-filemanager-from-tagged-candidate.yml
openshift/jag-csrs-deploy-frontend-from-tagged-candidate.yml
openshift/jag-csrs-file-manager.yml

Using variable substitution instead of hardcoding env var value

More infra adjustment

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.html
src/frontend/csrs-portal/src/app/components/communication/communication.component.scss

- CSRS-379: developed responsive design for Communication component

developed responsive design for Communication component

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts

- CSRS-283: corrected snowplow questions for step 0 and step 9

CSRS-283: corrected snowplow questions for step 0 and step 9

---

src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.html

- CSRS-283: fixed issue with Back button on Questionnaire

CSRS-283: fixed issue with Back button on Questionnaire

---

src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts

- CSRS-283: opened application pdf in new tab

CSRS-283: opened application pdf in new tab

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/landing/landing.component.scss
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.scss
src/frontend/csrs-portal/src/app/core/services/snowplow.service.ts
src/frontend/csrs-portal/src/snowplow.js

reversed PR 320

---

src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts
src/frontend/csrs-portal/src/app/core/services/snowplow.service.ts
src/frontend/csrs-portal/src/snowplow.js

- reversed to dev collection, removed leading spaces for questions 6 and 8

reversed to dev collection, removed leading spaces for question 6 and 8

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.ts
src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts

- updated questionnaire click by target urls

updated questionnaire click by target urls

---

src/frontend/csrs-portal/src/app/core/services/snowplow.service.ts
src/frontend/csrs-portal/src/snowplow.js

-changed on prod snowplow collector

changed on prod snowplow collector

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.scss

- CSRS-424: responsive design for applicant application

CSRS-424: responsive design for applicant application

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.scss

- CSRS-424: responsive design for applications

CSRS-424: responsive design for applications

---

src/backend/Csrs.Api/Models/ModelExtensions.cs
src/backend/Csrs.Api/Models/Party.cs
src/frontend/csrs-portal/src/app/api/api/message.service.ts
src/frontend/csrs-portal/src/app/api/model/party.model.ts
src/frontend/csrs-portal/src/app/api/swagger.json
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.scss
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- CSRS-366: developed other identity functionality

CSRS-366: developed other identity functionality

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.scss
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts

- CSRS-366: added missed show and hide classes

CSRS-366: added missed show and hide classes

---

src/frontend/csrs-portal/src/app/shared/components/header/header.component.html
src/frontend/csrs-portal/src/app/shared/components/header/header.component.scss
src/frontend/csrs-portal/src/app/shared/components/header/header.component.ts

- redeveloped header for 441px breakpoint (it is comment for CSRTS-427)

redeveloped header for 441px breakpoint

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- CSRS-408, 426: fixed Delete Childs defects

CSRS-408, 426: fixed Delete Childs defects

---

src/frontend/csrs-portal/src/app/components/questionnaire/questionnaire.component.ts

- CSRS-430: updated wording on questionnaire

CSRS-430: updated wording on questionnaire

---

src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs

- CSRS-431: added more invalid characters to eliminate from file name, shorted max URL length and added additional information into JsonReaderException

fixed CSRS-431

---

src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs

- CSRS-436: updated null exception

CSRS-436: updated null exception

---

src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs

- CSRS-436:  added logger information

CSRS-436:  added logger information

---

src/backend/Csrs.Interfaces.SharePoint/SharePointFileManager.cs

CSRS-440
- Fixed boolean check on response for successful folder creation
Manual testing.

Fixed folder creation response check

---

openshift/oidc-config.yml
src/backend/README.md
src/frontend/csrs-portal/src/assets/config/oidc.json

Shall be testing from OpenShift

[CSRS-446] KeyCloak Gold Standard Realm Integration

---

openshift/nginx-configmap.yml

Commented these lines to support new nginx image
Changes to support new nginx for fixing vulnerabilities

Commented these lines to support new nginx image

---

src/backend/Csrs.Services.FileManager/Dockerfile.rhel8
src/backend/Dockerfile.rhel8

[CSRS-448] Additional High Vul. Patch

---

src/frontend/csrs-portal/Dockerfile

[CSRS-448] Trying to Fix File Upload Failure

---

src/frontend/csrs-portal/src/app/shared/components/header/header.component.ts

Reverts bcgov/jag-csrs-portal-public#441

Revert "Csrs 451 - Update to login button #3"

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html

Added outage notification

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html

Remove Notification

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html

CSRS-493:  Added text to landing page.

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.html

CSRS-489-Added survey link to portal users

CSRS-489- Add survey link to portal users

---

src/frontend/csrs-portal/src/app/components/communication/communication.component.html

CSRS-489 - small change to remove extra underlining

CSRS-489 - small change to remove extra underlining

---

src/frontend/csrs-portal/package-lock.json
src/frontend/csrs-portal/package.json
src/frontend/csrs-portal/yarn.lock

Reverts bcgov/jag-csrs-portal-public#379

Revert "Bump ng-busy from 12.0.1 to 14.0.0 in /src/frontend/csrs-portal"

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

CSRS-488: Terms and Conditions updates

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/shared/components/footer/footer.component.html
src/frontend/csrs-portal/src/app/shared/components/footer/footer.component.ts

CSRS-488:  Added underline and Terms of Use to Footer

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

CSRS-571 - Change Wording on Conditions of Enrolment Messaging

---

src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html

-CSRS-571 - Content Update
Manual

CSRS-571 - Content Update

---

src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.html
src/frontend/csrs-portal/src/app/components/application-form-stepper/application-form-stepper.component.ts
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.html
src/frontend/csrs-portal/src/app/components/child-application-question/child-application-question.component.ts

- CSRS-567 - Portal Contact Information update
Manual Testing

Portal Contact Information Update

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html

- Canada Post service disruption notice removed
Manual testing

Landing Page update - Removed Canada Post service disruption notice

---

docker-compose.yml
src/frontend/csrs-portal/Dockerfile
src/frontend/csrs-portal/nginx.conf

CSRS-582 fix docker compose to work locally
Locally, with docker-compose and filling out questionaire

CSRS-582 docker compose fix

---

.gitignore
src/backend/Csrs.Api/Services/MessageService.cs

- CSRS-561 Confirmation of Portal Message and Document Upload
Fixed issue with the outbox messages not showing in the table
Made code reliable for null case management

CSRS-561 fixed issue with outbox messages parsing

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html

CSRS-Banner temporarily added for Canada Post disruption

---

src/frontend/csrs-portal/src/app/components/landing/landing.component.html

CSRS-596 Updated temp banner BCGEU strike
